name: Publish Runner Image by using Packer

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
      - '.github/workflows/packer-publish-image.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/actions-runner

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Delete huge unnecessary tools folder
        run: |
          echo "---Disk space before free---"
          df -h
          rm -rf /opt/hostedtoolcache
          cd /opt
          find . -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'
          echo "---Disk space after free---"
          df -h

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Continue free disk space
        run: bash ./scripts/util_free_space.sh

      - name: Setup `packer`
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        id: setup

      - name: Run `packer init`
        id: init
        run: |
          packer init ./images/ubuntu/templates/docker-ubuntu-24.04.pkr.hcl

      - name: Run `packer validate template`
        id: validate
        run: |
          packer validate ./images/ubuntu/templates/docker-ubuntu-24.04.pkr.hcl

      - name: Run `packer build`
        run: |
          packer build --var artifact_image_repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --var artifact_image_tag=rc-${{ github.run_number }} ./images/ubuntu/templates/docker-ubuntu-24.04.pkr.hcl

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image Docker Hub
        if: github.event_name == 'push'
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rc-${{ github.run_number }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rc-${{ github.run_number }}
